#compdef {{.Programs}}
# zsh completion for {{.Program}}.
#
# Generated by `{{.Short}} completion show zsh`; do not edit it. The commands and
# their flags are the ones this binary has, so the script is regenerated by
# installing a new one. Model ids, categories and vendors are not written here:
# they are asked for as they are needed, so `{{.Short}} catalog update` changes what
# is completed without this file being written again.
#
# Load it from ~/.zshrc, after compinit has run:
#
#   source <({{.Short}} completion show zsh)
#
# Or file it as _{{.Short}} in a directory on $fpath, which compinit then autoloads.

# {{.Func}}_words offers the words in $1 for the word being completed.
{{.Func}}_words() {
	local -a items
	items=(${=1})
	compadd -a items
}

{{.Func}}() {
	local cur prev exe
	# The name the command was invoked by, so that a binary that is not on
	# $PATH, or is installed under one of its two names, is the one asked.
	exe="${words[1]}"
	cur="${words[CURRENT]}"
	prev=""
	if [ "$CURRENT" -gt 2 ]; then
		prev="${words[CURRENT-1]}"
	fi

	if [ "$CURRENT" -le 2 ]; then
		{{.Func}}_words "{{.Nouns}}"
		return
	fi
	if [ "$CURRENT" -eq 3 ]; then
		case "${words[2]}" in
{{- range .Verbs}}
		{{.Noun}}) {{$.Func}}_words "{{.Verbs}}" ;;
{{- end}}
		esac
		return
	fi

	case "${words[2]} ${words[3]}" in
{{- range .Commands}}
	"{{.Name}}")
{{- range .FlagValues}}
		if [ "$prev" = "--{{.Flag}}" ]; then
			{{$.Func}}_words "{{.Values}}"
			return
		fi
{{- end}}
{{- if .Flags}}
		case "$cur" in
		-*)
			{{$.Func}}_words "{{.Flags}}"
			return
			;;
		esac
{{- end}}
{{- if .Arg}}
		# The argument is the word right after the verb, and nowhere else.
		if [ "$CURRENT" -eq 4 ]; then
			{{$.Func}}_words "{{.Arg}}"
		fi
{{- end}}
		;;
{{- end}}
	esac
}

# Sourced, the file runs as itself and has to register the function; autoloaded
# from $fpath, it runs as the function, under the name it was filed under. A
# word this script has nothing to say about is left to zsh, which completes a
# filename -- the path `file upload` takes, or the one behind `task run --input`.
if [[ "$funcstack[1]" == _{{.Short}}* ]]; then
	{{.Func}} "$@"
else
	compdef {{.Func}} {{.Programs}}
fi
