# bash completion for {{.Program}}.
#
# Generated by `{{.Short}} completion show bash`; do not edit it. The commands and
# their flags are the ones this binary has, so the script is regenerated by
# installing a new one. Model ids, categories and vendors are not written here:
# they are asked for as they are needed, so `{{.Short}} catalog update` changes what
# is completed without this file being written again.
#
# Load it from ~/.bashrc:
#
#   source <({{.Short}} completion show bash)

# {{.Func}}_words offers the words in $1 for the word being completed.
# cur belongs to the function below: bash scopes a local to the calls under it.
{{.Func}}_words() {
	COMPREPLY=($(compgen -W "$1" -- "$cur"))
}

{{.Func}}() {
	local cur prev exe
	COMPREPLY=()
	# The name the command was invoked by, so that a binary that is not on
	# $PATH, or is installed under one of its two names, is the one asked.
	exe="${COMP_WORDS[0]}"
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev=""
	if [ "$COMP_CWORD" -gt 1 ]; then
		prev="${COMP_WORDS[$((COMP_CWORD - 1))]}"
	fi

	if [ "$COMP_CWORD" -le 1 ]; then
		{{.Func}}_words "{{.Nouns}}"
		return
	fi
	if [ "$COMP_CWORD" -eq 2 ]; then
		case "${COMP_WORDS[1]}" in
{{- range .Verbs}}
		{{.Noun}}) {{$.Func}}_words "{{.Verbs}}" ;;
{{- end}}
		esac
		return
	fi

	case "${COMP_WORDS[1]} ${COMP_WORDS[2]}" in
{{- range .Commands}}
	"{{.Name}}")
{{- range .FlagValues}}
		if [ "$prev" = "--{{.Flag}}" ]; then
			{{$.Func}}_words "{{.Values}}"
			return
		fi
{{- end}}
{{- if .Flags}}
		case "$cur" in
		-*)
			{{$.Func}}_words "{{.Flags}}"
			return
			;;
		esac
{{- end}}
{{- if .Arg}}
		# The argument is the word right after the verb, and nowhere else.
		if [ "$COMP_CWORD" -eq 3 ]; then
			{{$.Func}}_words "{{.Arg}}"
		fi
{{- end}}
		;;
{{- end}}
	esac
}

# -o default leaves a word this script has nothing to say about -- the path
# `file upload` takes, or the one behind `task run --input` -- to the filename
# completion the shell would have done anyway.
complete -o default -F {{.Func}} {{.Programs}}
