package cli

import (
	_ "embed"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/tabwriter"
	"text/template"
)

// skillName is the directory the skill is installed under, and the name its
// front matter carries. Claude Code requires the two to agree.
const skillName = name

// The scopes `skill install` writes to: the project being worked on, which is
// what a skill about this repository's tooling usually belongs to, and the
// user, which is every project on this machine.
const (
	scopeProject = "project"
	scopeUser    = "user"
)

// Where Claude Code looks for skills. It reads one directory per skill, each
// holding a SKILL.md, under .claude in the project or in the home directory.
const (
	claudeDir  = ".claude"
	skillsDir  = "skills"
	skillFile  = "SKILL.md"
	claudeHome = "CLAUDE_CONFIG_DIR"
	dirMode    = 0o755
	skillMode  = 0o644
)

// What writing the skill did, as reported to the caller.
const (
	statusInstalled = "installed"
	statusUpdated   = "updated"
	statusUnchanged = "unchanged"
)

// markerPrefix opens the line every installed skill carries under its front
// matter. It is what tells a file this command wrote from one somebody else
// did, which is the whole of the overwrite rule below.
var markerPrefix = fmt.Sprintf("<!-- Generated by `%s skill install`", shortName)

// The skill itself. What it holds that changes -- the commands and what they
// are for -- is filled in from the command table, so a command added there is
// described to an agent without this file being touched.
//
//go:embed skill.md
var skillTemplate string

func bindSkillInstall(_ *env, fs *flag.FlagSet, _ []string) (binding, error) {
	scope := fs.String("scope", scopeProject, "where to install: "+scopeProject+" or "+scopeUser)
	force := fs.Bool("force", false, "overwrite a skill this tool did not write")
	run := func(e *env, args []string) error {
		return runSkillInstall(e, args, *scope, *force)
	}
	return binding{run: run}, nil
}

func runSkillInstall(e *env, args []string, scope string, force bool) error {
	if len(args) != 0 {
		return usagef("skill install: expected no arguments, got %d", len(args))
	}
	dir, err := skillDir(scope)
	if err != nil {
		return err
	}
	content, err := renderSkill()
	if err != nil {
		return err
	}
	path := filepath.Join(dir, skillFile)
	status, err := writeSkill(path, content, force)
	if err != nil {
		return err
	}
	return writeSkillState(e, skillState{Name: skillName, Scope: scope, Path: path, Status: status})
}

// skillDir resolves where the skill goes, as an absolute path: the answer is
// printed, and a relative one would not say which directory it was relative
// to.
func skillDir(scope string) (string, error) {
	switch scope {
	case scopeProject:
		// The current directory rather than the repository root: one rule,
		// and the path that is printed says where it landed.
		dir, err := filepath.Abs(filepath.Join(claudeDir, skillsDir, skillName))
		if err != nil {
			return "", fmt.Errorf("resolve the current directory: %w", err)
		}
		return dir, nil
	case scopeUser:
		home, err := userClaudeDir()
		if err != nil {
			return "", err
		}
		return filepath.Join(home, skillsDir, skillName), nil
	default:
		return "", usagef("skill install: unknown scope %q, expected %q or %q", scope, scopeProject, scopeUser)
	}
}

// userClaudeDir is the .claude directory of this user, which CLAUDE_CONFIG_DIR
// moves. A relative value is ignored rather than resolved against the current
// directory: a user-scope install that lands somewhere different in every
// directory it is run from is not one.
func userClaudeDir() (string, error) {
	if dir := os.Getenv(claudeHome); filepath.IsAbs(dir) {
		return dir, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("locate home directory: %w", err)
	}
	return filepath.Join(home, claudeDir), nil
}

// writeSkill puts the skill at path and reports what that did.
//
// A file this command wrote is replaced, because reinstalling is how a newer
// binary's skill is picked up. A file it did not write is left alone: it is
// somebody's own skill under a name that happens to collide, and overwriting it
// silently would destroy work no copy exists of. --force is for saying that it
// should go anyway.
func writeSkill(path, content string, force bool) (string, error) {
	status := statusInstalled
	switch existing, err := os.ReadFile(path); {
	case err == nil:
		if string(existing) == content {
			return statusUnchanged, nil
		}
		if !force && !strings.Contains(string(existing), markerPrefix) {
			return "", fmt.Errorf("%s was not written by %s; pass --force to overwrite it", path, name)
		}
		status = statusUpdated
	case !errors.Is(err, os.ErrNotExist):
		return "", fmt.Errorf("read %s: %w", path, err)
	}

	if err := os.MkdirAll(filepath.Dir(path), dirMode); err != nil {
		return "", fmt.Errorf("create skill directory %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), skillMode); err != nil {
		return "", fmt.Errorf("write skill %s: %w", path, err)
	}
	return status, nil
}

// skillDoc is what the template renders: the two names the tool is installed
// under, the marker that makes the file recognisable, and the command table.
type skillDoc struct {
	Name     string
	Program  string
	Full     string
	Marker   string
	Commands []skillCommand
}

// skillCommand is one command as the skill describes it, which is the same
// line the usage text is built from.
type skillCommand struct {
	Name    string
	Summary string
}

func renderSkill() (string, error) {
	doc := skillDoc{
		Name:    skillName,
		Program: shortName,
		Full:    name,
		Marker: fmt.Sprintf("%s (%s). Do not edit; reinstall to update. -->",
			markerPrefix, version()),
	}
	for _, c := range commands() {
		doc.Commands = append(doc.Commands, skillCommand{
			Name:    strings.TrimRight(c.noun+" "+c.verb+" "+c.args, " "),
			Summary: c.summary,
		})
	}
	rendered, err := template.New(skillFile).Parse(skillTemplate)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	if err := rendered.Execute(&b, doc); err != nil {
		return "", err
	}
	return b.String(), nil
}

// skillState is what the command reports: which skill was written, under which
// scope, where, and whether that changed anything.
type skillState struct {
	Name   string `json:"name"`
	Scope  string `json:"scope"`
	Path   string `json:"path"`
	Status string `json:"status"`
}

func writeSkillState(e *env, s skillState) error {
	if e.json {
		return writeJSON(e.stdout, s)
	}
	w := tabwriter.NewWriter(e.stdout, 0, 0, 2, ' ', 0)
	for _, row := range [][2]string{
		{"name", s.Name},
		{"scope", s.Scope},
		{"path", s.Path},
		{"status", s.Status},
	} {
		fmt.Fprintf(w, "%s\t%s\n", row[0], row[1])
	}
	return w.Flush()
}
